### ISSUE TITLE
@jorge Run application problem.

### ISSUE THREAD

**Issue by Miguelira** [IBMDataScience/dsx-shiny-apps#1]
@jorge good afternoon, I had a problem with the execution of your app. Actually I follow step by step from the site: https://github.com/IBMDataScience/dsx-shiny-apps. 
When I run the document the shiny app only showed me object '.xts_chob' not found. Can you give an advice to solve this problem?

**Comment by castanan** [comment]
@Miguelira I recently updated the predictions with the most recent info so you might be able to run the accidents app now
